javalite-common/src/main/java/org/javalite/common/Util.java
I remove unnecessary repetition code. 
I'm thinking of modify the "read" method, being perhaps:
```java
public static String read(InputStream in) throws IOException {
return read(in, null);
}
public static String read(InputStream in, String charset) throws IOException {
if(charset == null) {
charset = "UTF-8";
}
// ....
}
```
Setting the encoding `UTF-8` by default in the base method, What do you think?
=> Check the readFile method in Util.java

activejdbc/src/main/java/org/javalite/activejdbc/CallbackAdapter.java, activejdbc/src/main/java/org/javalite/activejdbc/CallbackListener.java, activejdbc/src/main/java/org/javalite/activejdbc/CallbackSupport.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/NumericValidator.java, activejdbc/src/test/java/org/javalite/activejdbc/Defect381_UpdateModifiedOnlyTest.java, activejdbc/src/test/java/org/javalite/activejdbc/ValidatorsTest.java
Please review and comment. I might have missed some cases - please see Defect381_UpdateModifiedOnlyTest.java for covered scenarios.
=> #381: update only what was changed

activejdbc/pom.xml, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/dialects/DefaultDialect.java, activejdbc/src/main/java/org/javalite/activejdbc/dialects/Dialect.java, activejdbc/src/test/java/org/javalite/activejdbc/ModelTest.java
I'm not sure if this was done the right way because I don't know how activejdbc does its parameterization, but it appears to be giving the correct output. 
I had to comment out a section that would give me strange errors if I left it in.
=> Adding a .toUpdate() method, issue #377

activejdbc/src/main/java/org/javalite/activejdbc/validation/length/AttributeLengthValidator.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/length/option/Exact.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/length/option/LengthOption.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/length/option/Max.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/length/option/Min.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/length/option/Range.java, activejdbc/src/test/java/org/javalite/activejdbc/AttributeLengthValidatorTest.java
Attribute length validator with validations on:
* **Maximum**: The attribute length must be *less than or equal* to the given value.
* **Minimum**: The attribute length must be *more than or equal* to the given value.
* **Exact**: The attribute length must be *equal* to a given value.
* **Range**: The attribute length must be *between* the given minimum and maximum length (inclusive).
=> Add attribute length validator.

activejdbc/src/test/java/org/javalite/activejdbc/AttributeLengthValidatorTest.java, activejdbc/src/test/resources/activejdbc_messages.properties, activejdbc/src/test/resources/activejdbc_messages_de_DE.properties
As per the request in #428, I've added an internationalization test.
=> Add an internationalization test.

activejdbc-gradle-plugin/build.gradle, activejdbc-gradle-plugin/pom.xml, activejdbc-gradle-plugin/src/main/groovy/org/javalite/instrumentation/gradle/ActiveJDBCInstrumentation.groovy, activejdbc-gradle-plugin/test-project/build.gradle, activejdbc-gradle-plugin/test-project/src/main/java/org/javalite/activejdbc/gradle/plugin/test/Example.java, activejdbc-gradle-plugin/test-project/src/main/resources/db/migration/V1__Create_example_table.sql, activejdbc-gradle-plugin/test-project/src/test/java/org/javalite/activejdbc/gradle/plugin/test/ExampleTest.java, activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/Instrumentation.java, activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/InstrumentationModelFinder.java
Loads the classes for instrumentation into a separate classloader instead of adding them to the root.
=> Fix the gradle plugin for use with the gradle daemon

activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/Paginator.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/NumericValidator.java, javalite-common/src/main/java/org/javalite/common/Base64.java, javalite-common/src/main/java/org/javalite/common/XmlEntities.java, javalite-common/src/main/java/org/javalite/http/Request.java
pmd:RedundantFieldInitializer - Redundant Field Initializer. 
https://dev.eclipse.org/sonar/rules/show/pmd:RedundantFieldInitializer
Faisal Hameed
=> Code quality fix - Redundant Field Initializer. 

activejdbc/src/main/java/org/javalite/activejdbc/Association.java, activejdbc/src/main/java/org/javalite/activejdbc/CaseInsensitiveMap.java, activejdbc/src/main/java/org/javalite/activejdbc/CaseInsensitiveSet.java, activejdbc/src/main/java/org/javalite/activejdbc/ColumnMetadata.java, activejdbc/src/main/java/org/javalite/activejdbc/LazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/Paginator.java, activejdbc/src/main/java/org/javalite/activejdbc/SuperLazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/BelongsToAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/BelongsToPolymorphicAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/Many2ManyAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/OneToManyAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/OneToManyPolymorphicAssociation.java, db-migrator/src/main/java/org/javalite/db_migrator/VersionStrategy.java
Reverts javalite/activejdbc#517
=> Revert "Code quality fix - "Serializable" classes should have a version id."

activejdbc/src/main/java/org/javalite/activejdbc/Configuration.java, activejdbc/src/main/java/org/javalite/activejdbc/ConnectionsAccess.java, activejdbc/src/main/java/org/javalite/activejdbc/DB.java, activejdbc/src/main/java/org/javalite/activejdbc/LazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModels.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelDelegate.java, activejdbc/src/main/java/org/javalite/activejdbc/Registry.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/CacheManager.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/EHCache3Manager.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/EHCacheManager.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/QueryCache.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/RedisCacheManager.java, activejdbc/src/main/java/org/javalite/activejdbc/web/ActiveJdbcFilter.java, db-migrator/src/main/java/org/javalite/db_migrator/DbUtils.java, db-migrator/src/main/java/org/javalite/db_migrator/Migration.java, db-migrator/src/main/java/org/javalite/db_migrator/MigrationResolver.java, db-migrator/src/main/java/org/javalite/db_migrator/VersionStrategy.java
squid:S1312 - Loggers should be "private static final" and should share a naming convention. 
https://dev.eclipse.org/sonar/rules/show/squid:S1312
Faisal Hameed
=> Code quality fix - Loggers should be "private static final" and should share a naming convention.

activejdbc/src/main/java/org/javalite/activejdbc/AbstractLazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/Configuration.java, activejdbc/src/main/java/org/javalite/activejdbc/ConnectionsAccess.java, activejdbc/src/main/java/org/javalite/activejdbc/DB.java, activejdbc/src/main/java/org/javalite/activejdbc/Errors.java, activejdbc/src/main/java/org/javalite/activejdbc/LazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModels.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelDelegate.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelFinder.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelRegistry.java, activejdbc/src/main/java/org/javalite/activejdbc/Paginator.java, activejdbc/src/main/java/org/javalite/activejdbc/Registry.java, activejdbc/src/main/java/org/javalite/activejdbc/RowProcessor.java, activejdbc/src/main/java/org/javalite/activejdbc/StatementCache.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/CacheManager.java, activejdbc/src/main/java/org/javalite/activejdbc/dialects/DefaultDialect.java, activejdbc/src/main/java/org/javalite/activejdbc/statistics/StatisticsQueue.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/ValidationBuilder.java, activejdbc/src/test/java/org/javalite/activejdbc/BaseTest.java, activejdbc/src/test/java/org/javalite/activejdbc/Defect381_UpdateModifiedOnlyTest.java, activejdbc/src/test/java/org/javalite/activejdbc/PaginatorTest.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/H2StatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/MSSQLStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/MySQLStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/OracleStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/PostgreSQLStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/SQLiteStatementProvider.java, javalite-common/src/main/java/org/javalite/test/jspec/JSpec.java
squid:S2293 - The diamond operator ("<>") should be used. 
https://dev.eclipse.org/sonar/rules/show/squid:S2293
Faisal Hameed
=> Code quality fix - The diamond operator ("<>") should be used.

javalite-common/src/main/java/org/javalite/http/Http.java, javalite-common/src/main/java/org/javalite/http/Patch.java
=> refs #302 (ActiveWeb) - PATCH request

activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/test/java/org/javalite/activejdbc/ModelTest.java
https://github.com/javalite/activejdbc/issues/629
Convenience method to fetch existing model from db or to create and insert new record.
=> Implement findOrCreateIt

activejdbc/src/main/java/org/javalite/activejdbc/Registry.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/HasMany.java, activejdbc/src/test/java/org/javalite/activejdbc/ModelTest.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/DB2StatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/H2StatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/MSSQLStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/MySQLStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/OracleStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/PostgreSQLStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/SQLiteStatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/test_models/Player.java, activejdbc/src/test/java/org/javalite/activejdbc/test_models/Team.java, activejdbc/src/test/resources/h2_schema.sql
=> Enhancement 664

activejdbc/src/test/java/org/javalite/activejdbc/dialects/DefaultDialectTest.java
- added testMany2ManyAssoc
- added testDeleteManyToManyAssociation
- added testSelectExist
- added testInsertStatement
- added testInsertParametrized
- added testUpdateStatement
=> Added some unit tests to DefaultDialectTest

activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java
Update MetaModel.java for issue https://github.com/javalite/activejdbc/issues/705 - fix problem with deleteChildrenShallow for different class loaders
=> Update MetaModel.java for issue https://github.com/javalite/activejdbc/issues/705 - fix problem with deleteChildrenShallow for different class loaders

activejdbc/src/test/java/org/javalite/activejdbc/ModelTest.java
Hi, this PR partially fixes #721
`ModelTest.java`
* remove Date field from test since the resulting query would have been dependent on the DBMS
Cheers
=> [Tests@MSSQL] - Fix ModelTest

activejdbc/src/main/java/org/javalite/activejdbc/dialects/MSSQLDialect.java, activejdbc/src/main/java/org/javalite/activejdbc/dialects/SQLiteDialect.java
Hi
When resolving issue #638 I didn't noticed that the test I have included would fail under SQLite.
This PR is meant to correct that mistake.
Cheers
=> [Test@SQLite] - Update SQLiteDialect overrideDriverTypeConversion to support empty date

activejdbc-kt/.gitignore, activejdbc-kt/pom.xml, activejdbc-kt/src/main/java/org/javalite/activejdbc/CompanionModel.kt, activejdbc-kt/src/main/kt/org/javalite/activejdbc/CompanionModel.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/CompanionModelTest.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/kt/test_models/Address.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/kt/test_models/Addresses.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/kt/test_models/People.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/kt/test_models/Person.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/utils/KtActiveJDBCTest.kt, activejdbc-kt/src/test/kt/org/javalite/activejdbc/utils/KtJdbcProperties.kt, activejdbc-kt/src/test/resources/database.properties, activejdbc-kt/src/test/resources/jdbc.properties, activejdbc-kt/src/test/resources/kt_h2_schema.sql, pom.xml
Hello,
I think I found a way to use ActiveJDBC with Kotlin without creating wrapper of removing the instrumentation (which is still required).
**As you know:**
- Static method inheritance won't be implemented in Kotlin (because considered as bad-practice by the core team).
- ActiveJDBC rely on static method inheritance to work.
**As example, the both following classes are equivalent:**
```java
import org.javalite.activejdbc.Model;
public class Person extends Model {}
```
```kotlin
import org.javalite.activejdbc.Model;
import org.javalite.activejdbc.CompanionModel
open class Person():Model() {
companion object:CompanionModel<Person>(Person::class.java)
}
```
The Kotlin one is longer but I think this is acceptable.
**How does this patch work ?**
- I create a class …
=> Add Kotlin to ActiveJDBC

activejdbc/src/test/resources/db2_schema.sql
Hi @ipolevoy 
I've noticed that DB2 tests were failing because there were past commits messing the `db2_schema.sql`.
This PR is meant to fix that.
Cheers
=> Tests@DB2 - Fix db2_schema.sql

activejdbc/src/main/java/org/javalite/activejdbc/dialects/OracleDialect.java, activejdbc/src/test/java/org/javalite/activejdbc/dialects/OracleDialectTest.java
This PR is meant to fix #757
Tests in error:
-   RawPaginatorSpec.shouldLoadOnlyRequestedColumns:134
-   JsonLog4jLayoutSpec.shouldPrintJsonLogValuesAndParams:102
As always, if you have any question, feedback or suggestion, please do not hesitate to say so :)
Cheers
=> Oracle Test fix - p2

activejdbc/pom.xml, db-migrator/pom.xml, pom.xml
- Updates PostgreSQL driver to the latest available version (42.2.5)
- Centralizes PostgreSQL driver version among all project
- Fixes the build issue introduced in f7acda1
=> #788 - Upgrade to the latest PostgreSQL driver + fix build

README.md
=> improved english

.travis.yml
Only until an alternate container can be procured
=> #835 - TravisCI - temporarily disable Oracle

activejdbc/src/main/java/org/javalite/activejdbc/Configuration.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelDelegate.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/QueryCache.java, activeweb-testing/src/main/java/org/javalite/activeweb/DBSpecHelper.java, activeweb-testing/src/main/java/org/javalite/activeweb/ViewSpec.java, activeweb/src/main/java/org/javalite/activeweb/Configuration.java, activeweb/src/main/java/org/javalite/activeweb/DynamicClassFactory.java, activeweb/src/main/java/org/javalite/activeweb/RequestDispatcher.java, activeweb/src/main/java/org/javalite/activeweb/RouteBuilder.java, activeweb/src/main/java/org/javalite/activeweb/freemarker/FormTag.java, activeweb/src/main/java/org/javalite/activeweb/freemarker/LinkToTag.java
=> Refactor to replace deprecated Class.newInstance()

activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/Logger.java
@ipolevoy ,  will you port it to the Java8-branch?
=> #982 - Make Logger.setLog(Log) public

activejdbc/src/main/java/org/javalite/activejdbc/Registry.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/HasManies.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/HasMany.java, activejdbc/src/test/java/org/javalite/activejdbc/IncludesTest.java, activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/H2StatementProvider.java, activejdbc/src/test/java/org/javalite/activejdbc/test_models/Customer.java, activejdbc/src/test/java/org/javalite/activejdbc/test_models/PhoneNumber.java, activejdbc/src/test/java/org/javalite/activejdbc/test_models/PostalAddress.java, activejdbc/src/test/resources/db2_schema.sql, activejdbc/src/test/resources/h2_schema.sql, activejdbc/src/test/resources/mssql_schema.sql, activejdbc/src/test/resources/mysql_schema.sql, activejdbc/src/test/resources/oracle_schema.sql, activejdbc/src/test/resources/postgres_schema.sql, activejdbc/src/test/resources/sqlite_schema.sql
Quoted column name that is an identifier in Oracle.
@ipolevoy , sorry for testing my DB schema changes this way.
=> #967 Repeatable has many

activejdbc-kt/pom.xml, activejdbc-kt/src/main/kt/org/javalite/activejdbc/CompanionModel.kt, pom.xml
Boyscoot's actions (in addition):
- Remove easy warnings of maven-resources-plugin during build
- Update Kotlin version to 1.3.61
This PR is the implementation of the [#999 issue](https://github.com/javalite/javalite/issues/999).
=> Integrate new functions to the Kotlin API

activejdbc-kt/pom.xml, activejdbc-kt/src/main/kt/org/javalite/activejdbc/CompanionModel.kt
Integrate new functions to the Kotlin API
Boyscoot's actions (in addition):
- Remove easy warnings of maven-resources-plugin during build
- Update Kotlin version to 1.3.61
=> [#999] Backport Kotlin patch from master

activeweb-testing/src/main/java/org/javalite/activeweb/AppIntegrationSpec.java, activeweb-testing/src/main/java/org/javalite/activeweb/ControllerSpec.java, activeweb-testing/src/main/java/org/javalite/activeweb/IntegrationSpec.java, activeweb-testing/src/main/java/org/javalite/activeweb/RequestBuilder.java, activeweb-testing/src/main/java/org/javalite/activeweb/SpecHelper.java, activeweb-testing/src/test/java/app/controllers/SessionFacadeSpec.java
=> #1115 - Fix a failing test in SessionFacadeSpec

activeweb/src/main/java/org/javalite/activeweb/AbstractControllerConfig.java, activeweb/src/main/java/org/javalite/activeweb/Configuration.java, activeweb/src/main/java/org/javalite/activeweb/FilterMetadata.java
[issue 1237](https://github.com/javalite/javalite/issues/1237)
=> Fix generics

activejdbc/src/main/java/org/javalite/activejdbc/MetaModels.java, activejdbc/src/test/java/org/javalite/activejdbc/ModelJSONSpec.java, javalite-common/src/main/java/org/javalite/json/JSONHelper.java, javalite-common/src/main/java/org/javalite/json/JSONList.java, javalite-common/src/main/java/org/javalite/json/JSONMap.java, javalite-common/src/test/java/org/javalite/json/JSONHelperSpec.java
#1247 - Remove implementation of XStream from the system as not secure
=> #1247 - Remove implementation of XStream from the system as not secure

javalite-common/src/main/java/org/javalite/json/JSONHelper.java
[#1351 - Add module registration to the JSONHelper](https://github.com/javalite/javalite/issues/1351)
=> #1351 - Add module registration to the JSONHelper
