activejdbc/pom.xml, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelDelegate.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/IdCompositeKeys.java, activejdbc/src/main/java/org/javalite/activejdbc/dialects/DefaultDialect.java, activejdbc/src/test/java/org/javalite/activejdbc/CompositePkTest.java, activejdbc/src/test/java/org/javalite/activejdbc/test_models/Composites.java, activejdbc/src/test/resources/h2_schema.sql, activejdbc/src/test/resources/mssql_schema.sql, activejdbc/src/test/resources/mysql_schema.sql, activejdbc/src/test/resources/oracle_schema.sql, activejdbc/src/test/resources/postgres_schema.sql, activejdbc/src/test/resources/sqlite_schema.sql, pom.xml
See:
https://groups.google.com/forum/m/#!topic/activejdbc-group/mSgxD1zwJIs
=> Limited Composite PK support

activejdbc-gradle-plugin/build.gradle, activejdbc-gradle-plugin/gradlew, activejdbc-gradle-plugin/gradlew.bat, activejdbc-gradle-plugin/settings.gradle, activejdbc-gradle-plugin/src/main/groovy/org/javalite/instrumentation/gradle/ActiveJDBCGradlePlugin.groovy, activejdbc-gradle-plugin/src/main/groovy/org/javalite/instrumentation/gradle/ActiveJDBCInstrumentation.groovy, activejdbc-gradle-plugin/src/main/resources/META-INF/gradle-plugins/org.javalite.activejdbc.properties
Hi, I really like ActiveJDBC and thought it might be useful to have a proper gradle plugin. 
The custom build script example in [javalite/activejdbc-gradle](https://github.com/javalite/activejdbc-gradle) works just fine (in fact the plugin is 99% just the code from the example), but does have the drawback that if the instrumentation process were ever to change everyone who copied the example would need to update their build.
If you are not interested in having this as part of the main repository let me know. I just assumed since the maven plugin is here perhaps you would want to merge in a gradle one too.
**Testing**
I converted the [gradle example to use the plugin here](https://github.com/jasoma/activejdbc-gradle/tree/gradle-plugin) so you can see the difference in the build script. …
=> Add a gradle plugin project for parity with maven

activejdbc-gradle-plugin/pom.xml
Choose which gradle wrapper script to execute based on OS family.
**Testing**
- Builds via maven on Windows-10 (powershell) and OSX
- maven install suceeds
- All artifacts (class, sources, and doc jars) present in the ouput
- `mvn exec:exec` succeeds for the plugin project on Ubuntu
**Caveats**
I had to comment out the builds of the `db-migrator` and `db-migrator-integration-test` modules since I don't have a MySql instance running which they expect. 
Could not fully test on Ubuntu since I get this error when trying to build the main `activejdbc` module:
```
Failed to execute goal org.javalite:activejdbc-instrumentation:1.4.12-SNAPSHOT:instrument (default) on project activejdbc: The parameters 'project' for goal org.javalite:activejdbc-instrumentation:1.4.12-SNAPSHOT:instrument are …
```
=> Setup the gradle plugin build to be platform agnostic #430

activejdbc-gradle-plugin/build.gradle
Fix an inconsistency between the maven/gradle build conventions that was causing the gradle-plugin jar to have classes at the wrong paths. Previously the gradle build was copying the entire `build/classes` dir into `target` and maven was constructing/signing the jar. The problem is this would include `main` as part of the paths in the jar:
```shell
$ jar tvf target/activejdbc-gradle-plugin-1.4.12-SNAPSHOT.jar 
0 Mon Nov 09 10:57:58 JST 2015 META-INF/
130 Mon Nov 09 10:57:56 JST 2015 META-INF/MANIFEST.MF
0 Mon Nov 09 10:57:56 JST 2015 main/
0 Mon Nov 09 10:57:56 JST 2015 main/org/
0 Mon Nov 09 10:57:56 JST 2015 main/org/javalite/
0 Mon Nov 09 10:57:56 JST 2015 main/org/javalite/instrumentation/
0 Mon Nov 09 10:57:56 JST 2015 main/org/javalite/instrumentation/gradle/
0 Mon Nov 09 10:57:52 …
```
=> Fix the class file copying from gradle output to maven output

activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/JavaAgent.java, activejdbc/src/main/java/org/javalite/activejdbc/Base.java, activejdbc/src/main/java/org/javalite/activejdbc/ConnectionsAccess.java, activejdbc/src/main/java/org/javalite/activejdbc/LogFilter.java, activejdbc/src/main/java/org/javalite/activejdbc/Messages.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelFinder.java, db-migrator/src/main/java/org/javalite/db_migrator/DbUtils.java, javalite-common/src/main/java/org/javalite/common/Inflector.java, javalite-common/src/main/java/org/javalite/http/Http.java, javalite-common/src/main/java/org/javalite/test/SystemStreamUtil.java, javalite-common/src/main/java/org/javalite/test/jspec/JSpec.java
This pull request is focused on resolving occurrences of rule: 
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:S1118
Faisal
=> Code quality fix - Utility classes should not have public constructors.

activejdbc/src/main/java/org/javalite/activejdbc/DBException.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/CacheManager.java, activejdbc/src/main/java/org/javalite/activejdbc/validation/ValidationException.java, db-migrator/src/main/java/org/javalite/db_migrator/MigrationManager.java
This pull request is focused on resolving occurrences of rules: 
squid:S1165:Exception classes should be immutable.
squid:S1181:Throwable and Error should not be caught.
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:S1165
http://dev.eclipse.org/sonar/rules/show/squid:S1181
Faisal
=> Code quality fix - General code quality fix-1

activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/InstrumentationModelFinder.java, activejdbc/src/main/java/org/javalite/activejdbc/RowProcessor.java, javalite-common/src/main/java/org/javalite/common/Convert.java, javalite-common/src/main/java/org/javalite/common/XmlEntities.java
This pull request is focused on resolving occurrences of rule: 
squid:S1197:Array designators "[]" should be on the type, not the variable.
findbugs:DM_NUMBER_CTOR:Performance-Method invokes inefficientNumber constructor
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:S1197
http://sonar.adroitlogic.com/rules/show/findbugs:DM_NUMBER_CTOR
Faisal
=> Code quality fix - General code quality fix-2

activejdbc/src/main/java/org/javalite/activejdbc/Configuration.java, activejdbc/src/main/java/org/javalite/activejdbc/ConnectionsAccess.java, activejdbc/src/main/java/org/javalite/activejdbc/DB.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModels.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java, activejdbc/src/main/java/org/javalite/activejdbc/ModelDelegate.java, activejdbc/src/main/java/org/javalite/activejdbc/Registry.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/CacheManager.java, activejdbc/src/main/java/org/javalite/activejdbc/cache/QueryCache.java, javalite-common/src/main/java/org/javalite/common/XmlEntities.java
This pull request is focused on resolving occurrences of rule: 
squid:ModifiersOrderCheck - Modifiers should be declared in the correct order.
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:ModifiersOrderCheck
Faisal
=> Code quality fix - Modifiers should be declared in the correct order

activejdbc/src/main/java/org/javalite/activejdbc/annotations/BelongsTo.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/BelongsToParents.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/BelongsToPolymorphic.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/DbName.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/IdGenerator.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/IdName.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/Many2Many.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/Table.java, activejdbc/src/main/java/org/javalite/activejdbc/annotations/VersionColumn.java
squid:S2333 - Redundant modifiers should not be used.
https://dev.eclipse.org/sonar/rules/show/squid:S2333
Faisal Hameed
=> Code quality fix - Redundant modifiers should not be used.

activejdbc/src/main/java/org/javalite/activejdbc/associations/Many2ManyAssociation.java, activejdbc/src/test/java/org/javalite/activejdbc/BaseTest.java, activejdbc/src/test/java/org/javalite/activejdbc/BelongsToParentsTest.java, activejdbc/src/test/java/org/javalite/activejdbc/CacheEventListenerTest.java, activejdbc/src/test/java/org/javalite/activejdbc/Issue137Spec.java, activejdbc/src/test/java/org/javalite/activejdbc/ModelTest.java, activejdbc/src/test/java/org/javalite/activejdbc/OrphanRecordTest.java, activejdbc/src/test/java/org/javalite/activejdbc/SetParentTest.java, activejdbc/src/test/java/org/javalite/activejdbc/TimeManagementSpec.java, activejdbc/src/test/java/org/javalite/activejdbc/ValidatorsTest.java
squid:S1161 - "@Override" annotation should be used on any method overriding.
https://dev.eclipse.org/sonar/rules/show/squid:S1161
Faisal Hameed
=> Code quality fix - "@Override" annotation should be used on any method overriding.

activejdbc/src/main/java/org/javalite/activejdbc/Errors.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/Model.java
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
https://dev.eclipse.org/sonar/rules/show/squid:S2864
Faisal Hameed
=> Code quality fix - "entrySet()" should be iterated when both the key and value are needed.

javalite-common/src/main/java/org/javalite/common/HumanDate.java
squid:S2185- Silly math should not be performed.
https://dev.eclipse.org/sonar/rules/show/squid:S2185
Faisal Hameed
=> Code quality fix - Silly math should not be performed.

javalite-common/src/main/java/org/javalite/http/Http.java
squid:S1444 - "public static" fields should be constant
https://dev.eclipse.org/sonar/rules/show/squid:S1444
Faisal Hameed
=> Code quality fix - "public static" fields should be constant.

activejdbc/src/main/java/org/javalite/activejdbc/Association.java, activejdbc/src/main/java/org/javalite/activejdbc/CaseInsensitiveMap.java, activejdbc/src/main/java/org/javalite/activejdbc/CaseInsensitiveSet.java, activejdbc/src/main/java/org/javalite/activejdbc/ColumnMetadata.java, activejdbc/src/main/java/org/javalite/activejdbc/LazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/MetaModel.java, activejdbc/src/main/java/org/javalite/activejdbc/Paginator.java, activejdbc/src/main/java/org/javalite/activejdbc/SuperLazyList.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/BelongsToAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/BelongsToPolymorphicAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/Many2ManyAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/OneToManyAssociation.java, activejdbc/src/main/java/org/javalite/activejdbc/associations/OneToManyPolymorphicAssociation.java, db-migrator/src/main/java/org/javalite/db_migrator/VersionStrategy.java
squid:S2057 - "Serializable" classes should have a version id.
https://dev.eclipse.org/sonar/rules/show/squid:S2057
Faisal Hameed
=> Code quality fix - "Serializable" classes should have a version id.

activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/InstrumentationModelFinder.java, activejdbc/src/main/java/org/javalite/activejdbc/DBException.java, activejdbc/src/main/java/org/javalite/activejdbc/StatementCache.java, app-config/src/main/java/org/javalite/app_config/AppConfig.java, javalite-common/src/main/java/org/javalite/common/Base64.java
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
https://dev.eclipse.org/sonar/rules/show/squid:S1213
Faisal Hameed
=> Code quality fix - The members of an interface declaration or class should appear in a pre-defined order.

activejdbc/src/main/java/org/javalite/activejdbc/Model.java
When eager loading more than one parent with ".include", the toJson() method appends a trailing comma after the item in the first parent, generating an invalid JSON string which causes errors in most parsers.
"Computer.findAll().include(Motherboard.class, Keyboard.class)" generates:
```json
[
{
"description":"ComputerX",
"id":1,
"key_id":1,
"mother_id":1,
"parents":{
"keyboards":[
{
"description":"keyboard-us",
"id":1
},
],
"motherboards":[
{
"description":"motherboardOne",
"id":1
}
]
}
}
]
```
After fix (valid JSON without trailing comma):
```json
[
{
"description":"ComputerX",
"id":1,
"key_id":1,
"mother_id":1,
"parents":{
"keyboards":[
{
"description":"keyboard-us",
"id":1
}
],
"motherboards":[
{
"description":"motherboardOne",
"id":1
}
]
}
}
]
```
SUGGESTION
Another approach would be …
=> Removing trailing comma when including parents in toJson() method

activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/ModelInstrumentation.java
This change detaches CtClass off ClassPool after instrumentation is done. This prevents from happening "model is frozen" exception while instrumentation is run as a task via Gradle 3 Daemon.
More information about the problem and solution is described in #537
=> #537 Fix of class is frozen while instrumentation is run as a task by Gradle Daemon

activejdbc/src/main/java/org/javalite/activejdbc/LazyList.java, activejdbc/src/test/java/org/javalite/activejdbc/IncludesTest.java, activejdbc/src/test/java/org/javalite/activejdbc/PolymorphicAssociationsTest.java, activejdbc/src/test/java/org/javalite/activejdbc/ToFromXmlSpec.java
Change method signature to return List<Map<String, Object>> instead of
List<Map>, which is more consistent with Model.toMap's return value of
Map<String, Object>.
=> Get rid of raw type usage in LazyList.toMaps

activejdbc/src/main/java/org/javalite/activejdbc/Registry.java
Maybe it will be better to treat schema name as database name for MySQL so table names like "dbname.tablename" would actually point to other database
=> Treat schema as catalog for MySQL

activejdbc/src/main/java/org/javalite/activejdbc/Model.java
Would be nice to have this small fix in the framework: https://github.com/javalite/activejdbc/issues/626
=> Parent information should be retrieved using parent connection.

activejdbc/src/test/java/org/javalite/activejdbc/ModelTest.java
Hello :)
This PR is meant to fix the current ActiveJDBC **tests** that seem to be **failing** under IBM **DB2**, as you can confirm here: http://ci.javalite.io/job/activejdbc-db2/20
The reported error is:
```java
org.javalite.activejdbc.DBException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-798, SQLSTATE=428C9, SQLERRMC=ID, DRIVER=4.13.127, query: INSERT INTO students (dob, first_name, id, last_name) VALUES (DATE '1965-12-01', 'Jim', 1, 'O''Connor''s')
at org.javalite.activejdbc.ModelTest.shouldGenerateCorrectInsertSQLWithReplacements(ModelTest.java:523)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-798, SQLSTATE=428C9, SQLERRMC=ID, DRIVER=4.13.127
at org.javalite.activejdbc.ModelTest.shouldGenerateCorrectInsertSQLWithReplacements( …
```
=> [DB2 Support] - ModelTest.java - Prevent test failure in DB2

activejdbc/src/main/java/org/javalite/activejdbc/validation/length/AttributeLengthValidator.java, activejdbc/src/test/java/org/javalite/activejdbc/AttributeLengthValidatorTest.java
Title says it all.  Need length validation on an optionally blank attribute.  If it is empty, the length validation shouldn't fail.  Tests included.
=> Adding support for null and blank values to the AttributeLengthValidator (issue #687)

activejdbc/src/test/resources/mssql_schema.sql
This partially fixes #721 by increasing a couple of VARCHAR sizes in `mssql_schema.sql` in order to match other DB schemas, this preventing test failures such as:
> http://ci.javalite.io/job/activejdbc-mssql/124/consoleFull
```java
ERROR!
org.javalite.activejdbc.DBException: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated., query: INSERT INTO genres (name) VALUES (?), params: Garage rock
at org.javalite.activejdbc.IncludesTest.shouldIncludeMultipleMany2ManyOverridesOnOneModel(IncludesTest.java:179)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated.
at org.javalite.activejdbc.IncludesTest.shouldIncludeMultipleMany2ManyOverridesOnOneModel(IncludesTest.java:179)
```
If you have any feedback or …
=>  [Tests@MSSQL] - Fix schema to prevent certain Test Failures #721

activejdbc/src/test/java/org/javalite/activejdbc/logging/JsonLog4jLayoutSpec.java
Hi
This PR is meant to partially fix #721 under MSSQL.
Fixes the following error while keeping compatibility with other DBMSs
```java
2018","thread":"main","logger":"org.javalite.activejdbc.LazyList","message":{"sql":"SELECT TOP 1 * FROM animals WHERE animal_id = ?","params":[1],"duration_millis":1,"cache":"miss"},"context":{"user_id":"234","user":"joeschmoe","email":"joe@schmoe.me"}}
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.087 sec <<< FAILURE! - in org.javalite.activejdbc.logging.JsonLog4jLayoutSpec
shouldPrintJsonLogValuesAndParams(org.javalite.activejdbc.logging.JsonLog4jLayoutSpec)  Time elapsed: 0.011 sec  <<< ERROR!
org.javalite.test.jspec.TestException: tested value does not contain expected value: SELECT * FROM animals WHERE animal_id = ?
at …
```
=> [Tests@MSSQL] - JsonLog4jLayoutSpec - adjust assertion to prevent test failure

activejdbc/pom.xml, activejdbc/src/main/java/org/javalite/activejdbc/dialects/MSSQLDialect.java, activejdbc/src/test/java/org/javalite/activejdbc/Defect638Test.java
Hi, this PR is meant to fix #638
Also updates `pom.xml` with the official [Microsoft JDBC driver](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc)
The fix prevents this kind of error when doing 
```java
FAILURE! - in org.javalite.activejdbc.Defect638Test
shouldNotThrowIllegalArgumentException(org.javalite.activejdbc.Defect638Test)  Time elapsed: 2.69 sec  <<< ERROR!
java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
at org.javalite.activejdbc.Defect638Test.shouldNotThrowIllegalArgumentException(Defect638Test.java:24)
Results :
Tests in error:
Defect638Test.shouldNotThrowIllegalArgumentException:24 » IllegalArgument Time...
```
Cheers
=> [MSSQL] - Updates MSSQLDialect to allow for empty string dates when creating the model from a Map

activejdbc/src/test/java/org/javalite/activejdbc/test/ActiveJDBCTest.java
Hi
This PR is meant to fix issue https://github.com/javalite/activejdbc/issues/729 by ensuring the Test Schema is committed into the DB before running tests.
This will ensure the tests will be executed against the proper version of the test schema, thus preventing errors.
Cheers
=> #729 - Ensure test schema is commited into the DB before running tests

activejdbc/src/main/java/org/javalite/activejdbc/Registry.java
I looked at the quoted table names test case and made the table name handling for H2 case sensitive for quoted names as well. I basically just moved the removal of the quotes to after the test for case sensitivity for H2. The tests are running on my machine.
=> Issue 707 - Use case sensitive names for quoted table names in H2

activejdbc/src/test/java/org/javalite/activejdbc/statement_providers/PostgreSQLStatementProvider.java
Hi @ipolevoy 
I've turned my eyes into PostgreSQL and I've noticed that the `CacheTest` was failing with the following error:
```java
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.476 sec <<< FAILURE! - in org.javalite.activejdbc.CacheTest
testCache(org.javalite.activejdbc.CacheTest)  Time elapsed: 0.05 sec  <<< ERROR!
org.javalite.activejdbc.DBException: 
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "doctors_pkey"
Detail: Key (id)=(4) already exists., query: INSERT INTO doctors (discipline, first_name, last_name) VALUES (?, ?, ?), params: physician, Sunjay, Gupta
at org.javalite.activejdbc.CacheTest.testCache(CacheTest.java:73)
Caused by: org.postgresql.util.PSQLException: 
ERROR: duplicate key value violates unique …
```
=> Tests@PostgreSQL - Fix CacheTest

.travis.yml, .travisci/setup.sh, activejdbc/pom.xml
Hello @ipolevoy
**TLDR**: This PR is meant to add support for building/testing with TravisCI, supporting the following DBMSs:
* H2
* MySQL
* PostgreSQL
* SQLite
* DB2 (using docker)
* MSSQL (using docker)
----
**Full story**
From what I've seen in http://ci.javalite.io, your current infrastructure is in need of an overhaul.
So, I'm not sure if you recall, but in https://github.com/javalite/activejdbc/pull/378#issuecomment-319521914 I've mentioned that I would like to create a CI Pipeline for ActiveJDBC using TravisCI.
Lately I've been working on that, thus all the Test Fixing commits 😛
**What's in it for you**
* Zero infrastructural costs for having ActiveJDBC tested for all* the supported DBMSs
* Low maintenance since TravisCI provides CI as a service - free for Open Source projects
* …
=> TravisCI - Support for H2, MySQL, DB2, SQLite, PostgreSQL and MSSQL

activejdbc-kt/pom.xml
@ipolevoy : I did two this in this PR.
1. The activejdbc-kt now produce a Jar of JavaDoc / KDoc.
2. I upgrade the Kotlin compiler version from 1.2.41 to 1.2.51 (fixes).
=> Generate jar of javadoc/kotlin-doc

activejdbc/src/main/java/org/javalite/activejdbc/dialects/OracleDialect.java
Hi
This PR is meant to fix issue #754 since it seams that Oracle's `DATE` is actually a `java.sql.Timestamp`. 
Source: https://stackoverflow.com/a/47713203
As always, if you have any question, feedback or suggestion, please do not hesitate to say so :)
Cheers
=> OracleDialect - override Driver Type Conversion for Dates - Fixes #754

activejdbc/src/test/java/org/javalite/activejdbc/FreemarkerSpec.java, activejdbc/src/test/resources/list_row.ftl
Hi @ipolevoy 
This PR is meant to fix issue #756.
Since the problem was due to the fact Oracle's date is actually a `timestamp` I opted to use a model with a timestamp instead of a `date` to avoid the issue altogether.
Do you think it's ok?
Cheers
=> #756 FreemarkerSpec's test fix attempt

.travis.yml, db-migrator-integration-test/src/test/project/test-project-environments/db.properties, db-migrator-integration-test/src/test/project/test-project-properties/database.properties, db-migrator-integration-test/src/test/project/test-project/pom.xml, db-migrator/src/main/java/org/javalite/db_migrator/JdbcPropertiesOverride.java, db-migrator/src/test/test-project/pom.xml
Change `db-migrator-integration-test` default `mysql` passwords according to https://docs.travis-ci.com/user/database-setup/#mysql
=> #785 - db-migrator-integration-test not passing on Travis due to security

javalite-common/pom.xml, javalite-common/src/test/java/org/javalite/common/RuntimeUtilSpec.java
I decided to skip RuntimeUtilSpec on Windows, because RuntimeUtil hangs in line 122. Did you consider using something like [Apache Commons Exec](http://commons.apache.org/proper/commons-exec/) to implement RuntimeUtil.execute()?
=> #798: skip RuntimeUtilSpec on Windows

.travis.yml
This PR aims to restore the Oracle tests by using a brand new Oracle Docker container.
Some notes about the container:
* Still an **unofficial** version: https://hub.docker.com/r/medgetablelevvel/oracle-12c-base but it is **based on the previous one** we used: `sath89/oracle-12c`, making it easier to deal with 
* Comes with an **already initialized database**, **saving us near 4.5 min** for not having to go through this step 👍 
* It's slightly bigger (resulting in a short increase of time for TravisCI to fetch it)
All in all, the **Oracle tests are now restored**, and the time between commit and test validation will be lower than before! Which, assuming the container will be stable, should be great news 😄
Fixes #835
Cheers
=> #835 - Travis CI - Restore Oracle tests

activejdbc/src/main/java/org/javalite/activejdbc/ScopeBuilder.java, activejdbc/src/test/java/org/javalite/activejdbc/ScopeSpec.java
This fix prevents an `UnsupportedOperationException` being raised by the implementation of the wrapped List upon calls to the `scope` method of `ScopeBuilder`.
=> #853 - Allow calling 'scope' on an existing ScopeBuilder object.

.travis.yml, .travisci/run_tests.sh, activejdbc/pom.xml
Hi @ipolevoy 
As promissed (better late then ever 😅), this PR aims to restore the DB2 test support, thus fixing https://github.com/javalite/activejdbc/issues/864
**Highlights**
* ✔️ Brand new official docker container from IBM - https://hub.docker.com/r/ibmcom/db2
* ✔️ Update DB2 JDBC Driver for DB2 11.5
* 👎  test execution is surprisingly 10x-15x slower than Oracle, which in my humble opinion was already slow...
Although I believe the build performance should be tunned, in my experience, it is better to have a broader DBMS test suit (with room for improvement) than nothing at all.
What are your thoughts?
As always, if you have any feedback or concern do not hesitate to say so :)
Cheers
=> #864 - TravisCI - Restore DB2 support

.travis.yml
* Migrate TravisCI VM from Ubuntu 14.04 (trusty) into Ubuntu 16.04 (xenial)
* Setup JDK11 builds
=> #870 - TravisCI - Configure Travis for Java 11

.travis.yml
Hi @ipolevoy 
Since we'll be mantaining 2 branches, I believe it would also be convenient to have TravisCI deploying the `java8` branch into maven repository, am I right?
This PR aims to rectify TravisCI configuration so we can achieve that 😉
=> #870 - TravisCI - Ensure java8 branch is also deployed into maven repo

activejdbc-kt/pom.xml, pom.xml
I took out the dokka-maven-plugin from the Maven's `package` phase to set it to the `pre-site` phase to fix the main issue. Because the last version of this plugin is not working well with JDK 11 their is still both warnings and errors when you execute the `mvn site` command but beside that everything is generated correctly.
Note that I have to upgrade the Kotlin version to the 1.3.50 in order to be able to make the Kotlin's compiler targeting JDK 11 and not only JDK 1.6 and 1.8. This will help in future releases.
=> #874 Fix build in failure due to dokka-maven-plugin on JDK 11

.travis.yml
The aim of this PR is to fix issue #962 by ensuring the `java8` branch is compiled with JDK8.
I'm almost sure the JDK11 commit wasn't there previously :/
=> #962 - TravisCI - Ensure java8 build is done with JDK8

.travis.yml, activejdbc-instrumentation/src/main/java/org/javalite/instrumentation/ModelInstrumentation.java
@ipolevoy , could you port this PR to the Java-8 branch, also?
I integration-tested the change with my project, removed the jacoco exclusion rules for the model classes and already found some unused model methods with the new report.
=> #887 - Add @Generated on methods generated by instrumentation

activejdbc/src/main/java/org/javalite/activejdbc/MetaModels.java
Managed to run the static metadata generator with "faulty" models. Please backport this to the appropriate branch, I just have Java 8 here.
=> [Java8]  Ignore metamodel serialization errors (fixes #1023) 

activejdbc/src/main/java/org/javalite/activejdbc/ModelFinder.java
We have couple of projects that doesn't build because of modelFile loaded 2 times.
The method to load modelFile `ClassLoader.getResources(String name)` may return more than one time the same file.
=> Avoid loading duplicate modelFile that will raise a InitException

activejdbc/src/main/java/org/javalite/activejdbc/MetaModels.java
When our service spins up, we immediately spin up some threads to perform scheduled jobs. When these threads use ActiveJDBC models, sometimes we see concurrency errors. Here's a sample stacktrace:
```
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1225)
at org.javalite.activejdbc.MetaModels.getModelRegistry(MetaModels.java:68)
at org.javalite.activejdbc.Registry.modelRegistryOf(Registry.java:106)
at org.javalite.activejdbc.Model.(Model.java:81)
at com.ktbyte.earth.model.ClassSessionStudentSwap.(ClassSessionStudentSwap.java:17)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) …
```
=> Handle concurrent calls to getModelRegistry

db-migrator-integration-test/src/test/project/test-project/pom.xml
Hi! I found the pom file of project **_org.javalite:db-migrator-maven-plugin-test-project:1.0-SNAPSHOT_** introduced **_2_** dependencies. However, among them, **_1_** libraries (**_50%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
org.freemarker:freemarker:jar:2.3.28:compile
---
Removing the redundant dependencies can reduce the size of project and prevent potential dependency conflict issues (i.e., multiple versions of the same library). More importantly, one of the redundant dependencies **_org.freemarker:freemarker:jar:2.3.28:compile_** incorporates a high-level vulnerability SNYK-JAVA-ORGFREEMARKER-1076795. As such, I suggest a refactoring operation for **_org.javalite:db-migrator-maven-plugin-test-project:1.0-SNAPSHOT_ …
=> Could org.javalite:db-migrator-maven-plugin-test-project:1.0-SNAPSHOTdrop off redundant dependencies? 

javalite-async/pom.xml
Maven will run all tests in a single forked VM by default. This can be problematic if there are a lot of tests or some very memory-hungry ones. We can fork more test VM by setting `<fork>1.5C</fork>`.
=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.
=> Dynamically adjust the number of Forked VM based on the number of CPU cores

activeweb/src/main/java/org/javalite/activeweb/Configuration.java, activeweb/src/test/java/app/controllers/issue1294/AbstractPrivateController.java, activeweb/src/test/java/app/controllers/issue1294/TestController.java, activeweb/src/test/java/org/javalite/activeweb/RouterControllerPathSpec.java
[#1294 - Lost controllers with non-public classes in inheritance and packet routing](https://github.com/javalite/javalite/issues/1294)
=> #1294 - Lost controllers with non-public classes in inheritance and packet routing
